id is:p2qmp9jx
Launching wandb...
Saving Final Model !
[36m(RLRunner pid=660325)[39m Exception raised in creation task: The actor died because of an error raised in its creation task, [36mray::RLRunner.__init__()[39m (pid=660325, ip=10.1.123.172, actor_id=5226d91edff74f5c81d1f8a901000000, repr=<runner.RLRunner object at 0x7fc8c8632390>)
[36m(RLRunner pid=660325)[39m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(RLRunner pid=660325)[39m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(RLRunner pid=660325)[39m   File "/home/ubuntu/LNS2-RL/runner.py", line 286, in __init__
[36m(RLRunner pid=660325)[39m     super().__init__(meta_agent_id)
[36m(RLRunner pid=660325)[39m   File "/home/ubuntu/LNS2-RL/runner.py", line 33, in __init__
[36m(RLRunner pid=660325)[39m     self.env._global_reset(0)
[36m(RLRunner pid=660325)[39m   File "/home/ubuntu/LNS2-RL/mapf_gym.py", line 627, in _global_reset
[36m(RLRunner pid=660325)[39m     self.dynamic_state = DyState(self.paths, self.global_num_agent, self.map.shape)
[36m(RLRunner pid=660325)[39m                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(RLRunner pid=660325)[39m   File "/home/ubuntu/LNS2-RL/dynamic_state.py", line 10, in __init__
[36m(RLRunner pid=660325)[39m     self.max_lens=max([len(path) for path in all_path])
[36m(RLRunner pid=660325)[39m                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(RLRunner pid=660325)[39m ValueError: max() arg is an empty sequence
[36m(RLRunner pid=660324)[39m     self.env._global_reset(0)
[36m(RLRunner pid=660324)[39m     self.global_set_world(cl_num_task)
[36m(RLRunner pid=660324)[39m   File "/home/ubuntu/LNS2-RL/mapf_gym.py", line 139, in global_set_world
[36m(RLRunner pid=660324)[39m     self.episode_len = EnvParameters.EPISODE_LEN[task_set]
[36m(RLRunner pid=660324)[39m                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
[36m(RLRunner pid=660324)[39m IndexError: list index out of range
[36m(RLRunner pid=660832)[39m     self.env._global_reset(0)
[36m(RLRunner pid=660830)[39m     self.env._global_reset(0)
[36m(RLRunner pid=660321)[39m     self.env._global_reset(0)
[36m(RLRunner pid=660323)[39m     self.valid_actions, self.obs, self.vector, self.train_valid = self.rl_local_reset_env(True)
[36m(RLRunner pid=660323)[39m                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(RLRunner pid=660323)[39m   File "/home/ubuntu/LNS2-RL/runner.py", line 158, in rl_local_reset_env
[36m(RLRunner pid=660323)[39m     self.env._local_reset(self.local_num_agent, first_time)
[36m(RLRunner pid=660323)[39m   File "/home/ubuntu/LNS2-RL/mapf_gym.py", line 645, in _local_reset
[36m(RLRunner pid=660323)[39m     new_agents = random.sample(range(self.global_num_agent), local_num_agents)
[36m(RLRunner pid=660323)[39m                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(RLRunner pid=660323)[39m   File "/home/ubuntu/miniconda/envs/lns2+RL/lib/python3.11/random.py", line 456, in sample
[36m(RLRunner pid=660323)[39m     raise ValueError("Sample larger than population or is negative")
[36m(RLRunner pid=660323)[39m ValueError: Sample larger than population or is negative
[36m(RLRunner pid=660834)[39m     self.env._global_reset(0)
[36m(RLRunner pid=660835)[39m     self.env_im._global_reset(0)
[36m(RLRunner pid=660831)[39m     self.env._global_reset(0)
[36m(RLRunner pid=660837)[39m     self.env._global_reset(0)
[36m(RLRunner pid=660836)[39m     self.env._global_reset(0)
[36m(RLRunner pid=660326)[39m     self.env._global_reset(0)
[36m(RLRunner pid=660833)[39m     self.env._global_reset(0)
[36m(RLRunner pid=660320)[39m     self.env._global_reset(0)
[36m(RLRunner pid=660322)[39m     self.env_im._global_reset(0)